# Note to cctools maintainers:
# When updating cctools versions, only the version and src_checksum variables
# should be modified.
# Get the checksum of the cctools-VERSION-source.tar.gz tarball as:
# openssl sha256  cctools-VERSION-source.tar.gz
# Note we use the name "ndcctools" as there is already another project in
# anaconda called cctools.

{% set name = "ndcctools" %}
{% set version = "7.4.1" %}
{% set src_checksum = "6e9bdd8d1fee8df8e49044780876931267a7c8b43a37e9f14f41be2084a96b03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ccl.cse.nd.edu/software/files/cctools-{{ version }}b1-source.tar.gz
  sha256: {{ src_checksum }}

build:
  number: 1
  skip: true  # [win]
  skip: true  # [osx and py==27]
  skip: true  # [osx and py==36]
  skip: true  # [python_impl=='pypy']
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - swig
    - make
    - libopenssl-static  # [not osx]
  host:
    - python
    - zlib
    - libnsl  # [not osx]
    - openssl
  run:
    - python
    - zlib
    - libnsl  # [not osx]
    - openssl
    - conda-pack

test:
  imports:
    - work_queue
  commands:
    - makeflow -h
    - work_queue_worker -h
    - work_queue_factory -h

about:
  home: http://ccl.cse.nd.edu/
  license: GPL-2.0-only
  license_file: COPYING
  summary: The Cooperative Computing Tools contains Chirp, Makeflow, JX, and Work Queue.
  description: |
    The Cooperative Computing Tools (cctools) are a collection of programs that
    enable large scale distributed computing on systems such as clusters,
    clouds, and grids. These tools are commonly used in fields of science and
    engineering that rely on large amounts of computing.
  doc_url: https://cctools.readthedocs.io
  dev_url: https://github.com/cooperative-computing-lab/cctools

extra:
  recipe-maintainers:
    - btovar
    - dthain
