# Note to cctools maintainers:
# When updating cctools versions, only the version and src_checksum variables
# should be modified.
# Get the checksum of the tarball as:
# curl -L https://github.com/cooperative-computing-lab/cctools/archive/refs/tags/release/VERSION.tar.gz | openssl sha256
# Note we use the name "ndcctools" as there is already another project in
# anaconda called cctools.

{% set name = "ndcctools" %}
{% set version = "7.15.11" %}
{% set src_checksum = "9e31fe14f60347e6a117e2b1b76df506a997c30dcabf4e4ba6f013241ef6797c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cooperative-computing-lab/cctools/archive/refs/tags/release/{{ version }}.tar.gz
  sha256: {{ src_checksum }}

build:
  number: 0
  skip: true  # [win or python_impl=='pypy']
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - m4
    - swig
    - make
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - zlib
    - libfuse3  # [not osx]
    - libnsl  # [not osx]
    - libopenssl-static
    - readline
    - openssl
    - cloudpickle
    - packaging
    - conda-pack
  host:
    - python
    - zlib
    - libfuse3  # [not osx]
    - libnsl  # [not osx]
    - libopenssl-static
    - readline
    - openssl
    - cloudpickle
    - conda-pack
  run:
    - python
    - libnsl  # [not osx]
    - openssl
    - readline
    - cloudpickle
    - conda-pack
    - packaging
    - rich
    - threadpoolctl

test:
  imports:
    - work_queue
    - taskvine
    - ndcctools.work_queue
    - ndcctools.taskvine
  commands:
    - makeflow -h
    - work_queue_worker -h
    - work_queue_factory -h
    - vine_worker -h
    - vine_factory -h

about:
  home: http://ccl.cse.nd.edu/
  license: GPL-2.0-only
  license_file: COPYING
  summary: Tools for large scale distributed computing.
  description: |
    The Cooperative Computing Tools (cctools) are a collection of programs that
    enable large scale distributed computing on systems such as clusters,
    clouds, and grids. These tools are commonly used in fields of science and
    engineering that rely on large amounts of computing.
  doc_url: https://cctools.readthedocs.io
  dev_url: https://github.com/cooperative-computing-lab/cctools

extra:
  recipe-maintainers:
    - btovar
    - dthain
